default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000
  database: <%= ENV["RAILS_DATABASE"] %>

development:
  <<: *default

test:
  <<: *default
  database: sike_test

production:
  <<: *default
